# Site settings
title: Jekyll Boilerplate
acronym: 
description: "A quick starter bolerplate"
site_name: Jekyll Boilerplate
keywords:
image: /assets/images/site-image.jpg
url: https://camariana.gm/
type: website
lang: "en-GB"

author: A Camariana
author_site: https://camariana.gm/
author_github: https://github.com/camariana/


# Global Configuration
source: src
timezone: Africa/Banjul


# Build Command Options
#baseurl: 


# Serve Command OptionsPermalink
#port: 40003
livereload: true
open_url: true


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Sass Settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed


# Collections Settings
collections_dir: my_collections
collections:
  projects:
    output: true
  journals:
    output: true